language: python
sudo: false
env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=py34-django18,coveralls
    - TOX_ENV=py27-django18,coveralls
    - TOX_ENV=py27-djangomaster,coveralls
    - TOX_ENV=py34-djangomaster,coveralls

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djangomaster
    - env: TOX_ENV=py34-djangomaster

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_script:
  - mysql -e 'create database lisa_api;'
  - mysql -uroot -e 'GRANT ALL PRIVILEGES ON lisa_api.* TO "lisa_api"@"localhost" IDENTIFIED BY "lisapassword";'
  - mysql -uroot -e 'FLUSH PRIVILEGES;'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/47c25ea28ce484eed9ca
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
