language: python
sudo: false
env:
    - TOX_ENV=py27-flake8
    - TOX_ENV=py27-docs
    - TOX_ENV=py34-django18
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-djangomaster
    - TOX_ENV=py34-djangomaster

services:
  - rabbitmq

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djangomaster
    - env: TOX_ENV=py34-djangomaster

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/47c25ea28ce484eed9ca
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

after_success:
  - coverage combine
  - coveralls