language: python
python: 2.7
sudo: false
env:
  matrix:
    - TOXENV=check
    - TOXENV=2.6,coveralls
    - TOXENV=2.6-nocover
    - TOXENV=2.7,coveralls
    - TOXENV=2.7-nocover
    - TOXENV=3.3,coveralls
    - TOXENV=3.3-nocover
    - TOXENV=3.4,coveralls
    - TOXENV=3.4-nocover
    - TOXENV=pypy,coveralls
    - TOXENV=pypy-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
before_script:
  - mysql -e 'create database lisa_api;'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/47c25ea28ce484eed9ca
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

