site_name: LISA API
site_url: http://api.docs.lisa-project.net/
site_description: LISA - API

repo_url: https://github.com/project-lisa/lisa-api

theme_dir: docs_theme

pages:
 - Home: 'index.md'
 - Tutorial:
    - 'Quickstart': 'tutorial/quickstart.md'
    - 'Plugins': 'tutorial/1-plugins.md'
 - Topics:
     - 'Internationalization': 'topics/internationalization.md'
     - 'Contributing to LISA': 'topics/contributing.md'